netlify/netlify-commons

.gitignore
glide.lock
glide.yaml
messaging/nats.go
metrics/counter.go
metrics/counter_test.go
metrics/env.go
metrics/env_test.go
metrics/errors.go
metrics/gauge.go
metrics/gauge_test.go
metrics/global.go
metrics/metrics.go
metrics/metrics_test.go
metrics/timer.go
metrics/timer_test.go
metrics/transport.go
metrics/transport/broadcast.go
metrics/transport/broadcast_test.go
metrics/transport/datadog.go
metrics/transport/datadog_test.go
metrics/transport/nats.go
metrics/transport/nats_test.go
metrics/transport/signalfx.go
metrics/transport/signalfx_test.go
stats/stats.go

This should be very compatible with the existing lib. We just swap it into place and configure the different transports.
I will be adding a signalFX and datadog transport too

port over and have nats transport

---

metrics/transport/signalfx.go
stats/stats.go

Also change to use cumulative counters for SignalFX.

Add dimensions support to stats

---

glide.lock
glide.yaml
messaging/nats.go
messaging/rabbit.go
metrics/cumulative_counter_test.go
metrics/env.go
metrics/global.go
metrics/reporter.go
mongo/db.go
nconf/logging.go
nconf/metrics.go

in using this lib I realized that having different packages was silly.

update to use the same config package

---

messaging/rabbit.go

- Create DialToRabbit function to get only a connection.
- Allow to create multiple consumers based on a connection.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Split Rabbit initialization to be more flexible.

---

nconf/configuration.go
nconf/configuration_test.go
nconf/reflect.go
nconf/reflect_test.go

This won't support pointers to strings/int/etc

add support for reflecting into missing stucts

---

metrics/counter.go
metrics/counter_test.go
metrics/cumulative_counter.go
metrics/cumulative_counter_test.go
metrics/env.go
metrics/env_test.go
metrics/gauge.go
metrics/gauge_test.go
metrics/global.go
metrics/metrics.go
metrics/metrics_test.go
metrics/reporter.go
metrics/timer.go
metrics/timer_test.go
metrics/transport/signalfx_test.go

We don't really care about these at the moment, but we do want a way to get them if they occur

Use async err handler not err returns

---

messaging/nats.go

So we have more information about slow connections.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Log pending messages in slow NATS connections.

---

glide.lock
glide.yaml
messaging/config.go
messaging/logrus_hook.go
messaging/nats.go
metrics/transport/nats.go
metrics/transport/nats_test.go
nconf/metrics.go

Also brings in the logrus hook.

add nats streaming

---

messaging/nats.go

I wrote this code in 3 services. I am tired of that.

create connect function for nats streaming

---

nconf/logging.go

huge shout out to David for helping me find this

disable panic handler for bugsnag

---

metrics/transport/signalfx.go

Do not report only .count, .sum, and .sumsquare for zero datapoints

---

.travis.yml
metrics/transport/signalfx.go
metrics/transport/signalfx_test.go
nconf/metrics.go

We are using mostly histogram values now.

Add option to disable timers reporting as counters

---

nconf/timeout.go

Starting of work for https://github.com/netlify/ansible/issues/1607

Add common configuration structs for HTTP client/server timeouts

---

glide.lock
glide.yaml
mongo/db.go

Use supported mgo fork

---

nconf/logging.go

This will help parsers in the future.

add a config value for quoting strings

---

nconf/configuration.go

This is more flexible to load configuration for testing and whatnot.

Add function to load configuration without a Cobra command.

---

messaging/config.go
messaging/logrus_hook.go
messaging/nats.go
mongo/db.go
nconf/nats.go
nconf/tls.go

This puts a lot of the configurations into the same package so they're easier to use. It also strips out some of the parts that were trying to be too clever by a half.

Refactor nconf layout

---

nconf/tracing.go

@rybit I quickly added this as mentioned in https://github.com/netlify/netlify-commons/pull/75#issuecomment-485910772

Provide config setup for tracer

---

messaging/nats.go
nconf/nats.go
nconf/tls.go

Implement new auth methods for NATS:
* user/password auth
* token auth
More info: https://nats.io/documentation/server/gnatsd-authentication/
Requirement for: https://github.com/netlify/nats-streamer/pull/2

[nats] Implement more auth methods

---

router/router.go

So you can mount other custom handlers.

Expose Mount from the chi Router.

---

server/server.go
server/server_test.go

make server package

---

go.mod
go.sum
nconf/args.go
nconf/bugsnag.go
nconf/logging.go

Looking to test this out on eventeer, so reviving the original implementation here. Two updates:
1. Passed the current app version to BugSnag config in order to track releases in the app.
2. Updates to the latest golang release.

Bugsnag updates

---

server/server.go
server/server_test.go

Pass project name to server

---

graceful/graceful.go

Adds a handler to shutdown daemon routines gracefully
This is mostly made for http.Server which exposes a Shutdown method taking a context for timeout

Add package "graceful"

---

util/atomic_bool.go
util/atomic_bool_test.go

Simple wrapper around Int32 atomic's to provide an atomic boolean.

Pull in AtomicBool from eventeer.

---

http/http.go
http/http_test.go

See https://github.com/netlify/bitballoon/issues/5376

Fix for internal issue bitballoon/5376

---

.github/workflows/fossa.yml

- had to add some module configuration for fossa to work because netlify-commons is a library and has no main package

fix: add fossa config

---

.github/workflows/build.yml

I think we may have lost this with move to GA?

Add back 1.14.x testing

---

nconf/bugsnag.go

This will allow them to display better error traces.

Add ProjectPackages to Bugsnag's configuration

---

server/server.go

I saw us listening in a bunch of services, this does it automatically.

make it automatically shutdown

---

kafka/consume.go

Closes https://github.com/netlify/netlify-commons/issues/164
This PR adds a new constructor on the Kafka package for creating a Consumer detached from Consumer Groups.
Note the following (added in comments):
> A detached consumer will work out of consumer groups for partition assignment and rebalance, however it needs
>       permission on the group coordinator for managing commits, so it needs a consumer group in the broker.
>       In order to simplify, the default consumer group id is copied from the configured topic name, so make sure you have a
>       policy that gives permission to such consumer group.
Behaviour workflow follows recommendations from the creator of `librdkafka` - https://github.com/confluentinc/confluent-kafka-go/issues/534
)

feat(kafka): add detached consumer

---

kafka/kafkatest/utils.go

This PR adds the missing methods for the `FakeKafkaConsumer`, implementing then `Consumer` interface.
cc @aarushik93

fix(kafkatest): add missing fake consumer methods

---

router/router_test.go
tracing/req_tracer_test.go

Fix tests around status code in tracing

---

featureflag/config.go
featureflag/featureflag.go

```
#[serde(rename_all = "camel_case")]
```

Fix de/ser tags on launchdarkly config

---

featureflag/featureflag.go
featureflag/featureflag_test.go

Guess i do too much Rust to not expect implicit copying of values...
_Fixes https://github.com/netlify/netlify-commons/issues/199_

Fix ld logging config

---

ntoml/netlify_toml.go

Adding fields permitted in [https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file](file-based configuration).

Add functions and edge_handlers to netlify toml

---

util/duration.go

- makes util.Duration implement the TextUnmarshaler interface so that we can use envconfig to read this into config structs from env variables
- tested and works!

feat: make util.Duration implement the TextUnmarshaler interface

---

server/options.go
server/server.go

fixes https://github.com/netlify/netlify-commons/issues/177
This should also be extensible for other settings as they come up

take optional Opts for modifying the http server

---

instrument/doc.go

I just started using this and figured that benefitting from the doc I just made by myself, but also realized that it can use a bit more real-world example.

chore(instrument): update godoc for instrument to have better test example

---

featureflag/featureflag.go
featureflag/mock.go

add AllEnabledFlagsUser to Client interface

fix: add AllEnabledFlagsUser to Client interface

---

.github/workflows/fossa.yml

Default branch is now main, update workflow accordingly

Update fossa to point to main

---

server/server.go
server/server_test.go

https://github.com/netlify/go-service-boilerplate/pull/54 -- this is a nice to have.

chore: add env to api info

---

featureflag/global.go

Please include a summary of the changes in this PR, as if it were a changelog. Include links to issues if possible.
If there are any breaking changes list them below with an upgrade guide.
BREAKING CHANGES:

feat: at Int variation to global feature flag client

---

.github/pull_request_template.md

Adds a small note about using release-please for release.

chore: add note about release-please

---

.github/CODEOWNERS

NOTICE: If this pull request does not apply to your repository, please reach out to #internal-security-n-compliance. Please review and merge this PR to update the CODEOWNERS file to include the recently standardized team names

docs: CODEOWNERS update 202206

---

ntoml/netlify_toml.go
ntoml/netlify_toml_test.go

Addresses: https://github.com/netlify/netlify-commons/issues/347
When looking into https://github.com/netlify/buildbot/issues/2141 we saw that files in `yaml`, `yml` and `json` are still supported in `netlify-commons/ntoml` package.
But in `build` we only make use of `netlify.toml` https://github.com/netlify/build/blob/60523200de880d86716acb6079e2699e32cd90f9/packages/config/src/path.js#L52
This PR removes all logic related to support the different .yaml/.yml/.json files

chore: remove support for netlify.json/.yaml/.yml
