netlify/netlify-commons

- stats/stats.go
- stats/stats_test.go
The stats package was going to put out a lot of lines potentially, this means it will be only one. And it makes logging at all optional.
Also a test.
> refactor the stats package to make better experience

- metrics/transport/signalfx.go
We were reporting timers as cumulative counters. This gives them a natural rollup of rate/sec..which doesn't necessarily make sense.
> update to make timers reported as counters

- graceful/graceful.go
- graceful/graceful_test.go
This is derived heavily from https://github.com/netlify/gocommerce/pull/65/files
It is intentionally split out into Bind and Listen methods (with a ListenAndServe) so that testing is easier. It also intentionally uses the listener directly because it supports using 0 as a port and letting the system decide the port.
> create the graceful server package

- graceful/graceful.go
- graceful/graceful_test.go
We were having the case that this would timeout because we would be waiting for the exit signal on shutdown and the listen to exit. This fixes that I think.
> close a channel to indicate the server is closing

- tls/tls.go
In this case we allow for using the values directly, not from file. It is good for kube services.
Also, if no CA is specified we will fall back to the system ones.
> set TLS values directly

- tls/tls.go
With the previous code, it uses the system certificates if a CA cert is provided
> [tls] Fix CA cert conditional

- glide.yaml
- nconf/env.go
- nconf/metrics.go
- tls/tls.go
We are moving to support environmental configuration, this adds some tags and cleanup to make that easier. We can't do nil values with env configs, so we need to rely on empty strings or enabled flags
> support env configuration

- messaging/nats.go
- messaging/rabbit.go
The TLS configuration can be nil, meaning we don't want TLS. We need to respect that. Also adds some debugging messages to the rabbitMQ connection code and the envconfig tags
> support for optional TLS in rabbit and nats

- nconf/env.go
- nconf/env_test.go
We should handle if there is no .env file. But if you specify a file we should error if it is missing.
> handle missing .env files

- discovery/main.go
- glide.lock
- glide.yaml
- messaging/nats.go
- messaging/rabbit.go
* Get a list of hosts from a DNS name
* Use a DNS name for configuring Rabbit and Nats
> [discovery] Add DNS discovery methods. Rabbit and Nats config to support DNS discovery

- ntoml/netlify_toml.go
- ntoml/netlify_toml_test.go
We were returning a custom error, that made it hard to _optionally_ specify paths for a toml file. Now we throw an error if we don't find it like before, but provide a way to check if we actually care
> return a not found error not custom error

- glide.lock
- glide.yaml
- nconf/logging.go
take a look at this [bug report](https://app.bugsnag.com/netlify/bitballoon-production/errors/59d7e8a8a27120001878c890?filters%5Bevent.since%5D%5B%5D=1h&filters%5Berror.status%5D%5B%5D=open)
```
import (
"errors"
"fmt"
"os"
"time"
"github.com/netlify/netlify-commons/nconf"
)
func main() {
log, err := nconf.ConfigureLogging(&nconf.LoggingConfig{
BugSnag: &nconf.BugSnagConfig{APIKey: os.Getenv("BUGSNAG_KEY")},
Level:   "debug",
})
if err != nil {
panic(err)
}
<-time.After(time.Second)
log.WithError(errors.New("FAIL TEST")).Error("Test")
<-time.After(time.Second)
fmt.Println("exiting")
}
```
It looks like there is a bit of a race here ~ we _could_ add a recover block too, but that won't catch if we return/exit too fast.
> add an optional bugsnag hook

- nconf/metrics.go
This fixes envconfig loading of the default dimensions.
> Change config default dimensions to map[string]string

- mongo/db.go
Connect to nodes that belong to the configured replica set
> [mongo] Use the primary node only if it belongs to the given replica set

- nconf/configuration.go
If the config file has a YAML extension, parse it as a YAML. Otherwise use JSON (keep old behaviour)
Why we want this now? Because it's easier to generate YAML config files using consul-templates, and we are moving netlify-server to K8S, where we use consul-template.
> Support YAML configurations

- discovery/main.go
Most of our services use that method and it makes more sense here.
> Add DiscoverServersAsStrings.

- .travis.yml
We want to go to modules we need to then be on 1.11+
> only use go 1.11+

- graceful/graceful.go
- graceful/graceful_test.go
- http/http.go
- http/http_test.go
This adds a SafeDialContext method that can be used when instantiating a
http client to make sure that it will never be able to dial reserved IP ranges.
> Add SafeDialContext method

- go.mod
- nconf/args.go
- nconf/args_test.go
- nconf/bugsnag.go
- nconf/logging.go
We have a bunch services that re-implement configuration loading. This is an attempt at simplifying that.
What I'm thinking it is then used something like this:
```
args := new(nconf.RootArgs)
cmd := &cobra.Command{
Run: func(_ *cobra.Command, _ []string) {
config := conf.DefaultConfig()
log := args.Setup(config)
.....
}
}
cmd.PersistentFlags().AddFlag(args.PrefixFlag())
cmd.PersistentFlags().AddFlag(args.ConfigFlag())
```
I'm def open to any stuff we can do to simplify that boiler plate.
> RootArg structure for easier config

- router/errors.go
- router/errors_test.go
- router/middleware.go
Relates to https://github.com/netlify/netlify-commons/pull/88.
`HandleError` should be ideally only be called when the error is not nil. As we can't ensure that, I added a change in that function in order to early return whenever `err` is nil.
Also added tests for `HandleError` func.
>  HealthCheck middleware only handles non-nil errors

- server/server.go
- server/server_test.go
This tweaks the `APIDefinition` interface to include full lifecycle support (Start + Stop). This allows the API to perform a clean shutdown like releasing and removing Consul locks. This was the remaining piece to allow Eventeer to remove its Server implementation.
> API lifecycle support

- http/http.go
- http/http_test.go
This adds a tracing method to a client that will make sure
any request to a reserved IP is canceled at DNSDone time
> Add a SafeHttpClient method

- router/middleware.go
- server/server.go
- server/server_test.go
Whenever an api implements the `Healthy` method, it will be used to run a custom healthcheck.
- Tests added
> Allow a server api to implement a custom healthcheck

- server/server.go
tl;dr: Allow active connections/requests to drain gracefully during shutdown.
When calling `Server.Shutdown()` the listening Go routine will return immediately and no new connections will be accepted. However, Shutdown will block until all active connections are finished or the context times out. Therefore, we must wait until Shutdown returns before we continue shutting down the API and eventually exiting the process.
> Wait for connections to drain.

- router/errors.go
- router/errors_test.go
- router/middleware.go
Router component wasn't able to handle nil pointer to type `HTTPError`, meaning the following simple handler 
```go
func(_ http.ResponseWriter, _ *http.Request) *HTTPError {
return nil
}
```
was ending with a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```
`return nil` is returning a nil pointer to type `HTTPError`, which is later on passed to https://github.com/netlify/netlify-commons/blob/91f500e0a2b59a8667d48df8f2cbeea2160da991/router/errors.go#L88
As you can see, the first arguments expects the interface `error`, which is completely fulfilled.
According to [Go FAQS](https://golang.org/doc/faq#nil_error):
> An interface value is nil only if the V and T are both unset
In that case, value is `nil` by type is `*HTTPError` so when this …
> fix(router): early return when zero vallue of err in HandleError

- util/atomic_bool.go
This is a slight tweak to the previous AtomicBool interface. Essentially as a consumer instead of:
```
struct {
isRunning *util.AtomicBool
...
}
```
you use:
```
struct {
isRunning util.AtomicBool
...
}
```
This hides the pointer abstraction behind an interface for the consumer.
> Slight interface tweak for AtomicBool

- ntoml/netlify_toml.go
Buildbot can panic with an error like this: [humio link](https://cloud.us.humio.com/netlify-us-production/search?query=kubernetes.pod.name%3Dbuild-5eba58546f64a8f0f1a0b34d&live=false&start=1589269284331&end=1589272215404&fullscreen=false&widgetType=list-view&columns=%40rawstring%3A%3Aauto&newestAtBottom=true&showOnlyFirstLine=false)
We're attempting to stat a filepath in this code, but only checking for one error case: that the file wasn't found.
I'm guessing we're hitting permission denied because the user provided a path outside the working directory (https://golang.org/pkg/os/#IsPermission)
I think it would be nice to warn if we're ignoring some path because of an error, but we don't have access to a logger here and returning early with the error would cause us to fail builds that …
> Fix panic in ntoml when checking paths

- ntoml/netlify_toml.go
- ntoml/netlify_toml_test.go
Made a small mistake in my last PR :upside_down_face: 
We want to check that the error *is* nil when we stat the file. Added a test to catch this.
> Fix err check in ntoml path checker

- ntoml/netlify_toml.go
We serialize the config returned by Netlify Config back to this type. Only including package name for now, since that's the only plugins field that will be handled by Buildbot for plugins GA.
Part of https://github.com/netlify/buildbot/issues/746
> Add plugin package names to netlify.toml

- metriks/metriks.go
- metriks/metriks_test.go
I noticed in some of our PRs there was some cumbersome code (imho). Essentially you had to do a bunch of boilerplate to add a label. I thought that this would make things cleaner. I am pretty sure that we could pass through to always with labels (or an empty), but this seemed safer
> take variadic args for labels

- tracing/logging.go
- tracing/req_tracer.go
Add method to set a final field given a context.
This is useful when you want to add entries to the canonical api log from a component called by a request handler.
Signed-off-by: David Calavera <david.calavera@gmail.com>
> Set final field with context.

- metriks/config.go
- metriks/metriks.go
- metriks/metriks_test.go
`Name` config field maps to Datadog sink `hostname` field. It is only used by
armon/go-metrics lib and in a really non-well documented way.
It is basically used for removing from the metrics key the hostname in
favor of adding it (manually by the user) as tag. The library creator
explains that it makes sense since Datadog is multidimensional so the
tags should be used instead.
This is causing issues like sending metrics without the expected prefix: I.e.:
- Expected: `my-app.hits`
- Got: `hits`
See https://github.com/armon/go-metrics/blob/master/datadog/dogstatsd.go#L63-L82
We totally disagree.
> fix(metriks): force empty Datadog sink hostname. Service name always in prefix.

- router/errors.go
- router/errors_test.go
- router/middleware.go
- router/middleware_test.go
- router/options.go
- router/router.go
- router/router_test.go
- server/server.go
- server/server_test.go
* Adds the option (and defaults on) a recoverer middleware
* changes the `APIHandler` to use `error`
The latter is because of learnings from: https://golang.org/doc/faq#nil_error (thanks @smoya!). It should be transparent to code using it. If using the `HandleError` it already handles this case
If this gets merged I think we should up the version number to indicate a breaking change.
> change the APIHandler add the Recoverer

- metriks/config.go
- metriks/metriks.go
- nconf/args.go
- nconf/args_test.go
The goal here is to have a standard names and configuration that people can use. We can change the boilerplate templates used to provide these by default too.
This is slightly breaking change in that you have to provide the "serviceName" to the args now. We should consider unifying the other calls (e.g. in `server`) too.
> make tracing and metrics part of the default config

- router/errors.go
- router/errors_test.go
- router/middleware.go
- tracing/context.go
- tracing/logging.go
- tracing/req_tracer.go
- tracing/tracer.go
In cert-store we were trying to pull the request ID from the context, so we had to jam it in there. This is probably a common pattern (e.g. going to make a secondary request).
I decided to use the `Tracer` (vs adding an explicit key) so that there was no chance of drift. Plus it made it easy. I'm def open if people don't like this (I kinda don't like this whole package).
> make the request ID accessible from context

- .github/workflows/build.yml
- go.mod
Recently released. I think supporting latest two is the default.
> Upgrade to Go 1.15

- mongoclient/db.go
- mongoclient/options.go
fixes https://github.com/netlify/netlify-commons/issues/146
I was thinking of adding struct tags around validation/mapstructure/envconfig to the `Config` object so that it is usable by default. Then if someone wants to roll their own config, they can use the `Option` interface.
> add options for the mongo client

- .github/dependabot.yml
- go.mod
- go.sum
This uses the GitHub-native dependabot.
Let's see if it works well for us.
> Automatic dependency updates

- metriks/metriks.go
- nconf/args.go
- nconf/events.go
We have a few hard to decode events in datadog that make it very hard to understand what is going on. 
There are docker ones:
There are spinnaker ones:
This gives us some that are in our common code:
Hopefully this can be clearer and we can tweak more easily as we discover wants/needs. 
Things to note:
- pod/hostname is based on a kube env var that I'm checking. Not sure if this is the best way. 
- version/service are from our code
- env/zone/hostname and pretty much all the rest come from the datadog agent. These mostly seem like overkill to me but...I don't think we can get rid of them.
> make start stop events for a service

- tracing/opentracing.go
This method is used in a few services and it is pretty useful. I think that it makes sense to import here. Also, anything to make opentracing more usable I'm all for
> add a LogErrToSpan

- server/server.go
- server/server_test.go
Saw in a bunch of our services we were passing these values around a lot. Easy to swap order too. This makes it a bit cleaner I think
> Use a struct for meta info

- featureflag/global.go
- nconf/args.go
I was looking into using this in a service and noticed that it seems like we can use a global one. I am not 100% sure that the underlying launch darkly client is threadsafe, but we had that risk before anyways.
This also ties it into the config defaults
> make a global client for feature flagging

- parser/user_traffic.go
- parser/user_traffic_test.go
Kick's off a parser package with a no frill's user traffic parser to start with. It's based on some previous work from @rybit in an old metering package. While this generally doesn't try to proactively clean up the log line in anyway - there was one case where we decided to clean up the result. Namely in that we proactively strip trailing comma's from `sid` , since this was a some what common occurrence.
> user traffic log line parser

- router/middleware.go
- router/middleware_test.go
- tracing/context.go
When debugging a panic this should introduce the requets that caused it and then a key we can use to sort from because humio messes that up.
> make the recoverer tie back to a request

- router/errors.go
- router/errors_test.go
- router/middleware.go
- router/middleware_test.go
- tracing/req_tracer.go
In fighting the cert-store I noticed that when we fall into `HandleError` which is in the case of a panic or unexpected error we don't really cleanup nicely.
This adds that non-nil errors:
- unexpected ones go to bugsnag. This is because returning a 404 isn't an error in and of itself
- we always call `Finish` on the tracing. This is in the event of a panic
- we record unexpected errors in datadog
- we do complete the span if it isn't set
> handle errors better in the tracing and spans

- featureflag/featureflag.go
- featureflag/mock.go
- go.sum
If we want to test features against custom user attributes, we need be able to build a more complex user object when passing to the Enabled and Variation checks. This PR adds `*User` methods to expose the same checks, but instead of taking a simple string key takes a LD `User` instead. This allows the consumer to use the [`UserBuilder`](https://pkg.go.dev/github.com/launchdarkly/go-server-sdk#UserBuilder) to build a complex user object with attributes.
This does mean that we are now exposing the LD client internals directly to consumers, if they want to use these new APIs. At the moment I think this is fine as most consumers will stick to simple key-based methods only. This will allow us to experiment with more custom user attributes and build common patterns. We can eventually fold those …
> Expose LD users to enable custom attributes.

- kafka/config.go
- kafka/integration_test.go
Logs channel was closed when the context got canceled. This ends in a race condition where the `confluent-kafka-go` library tries to still send log messages (client not closed yet) to a closed channel, producing a  panic: `panic: send on closed channel`
> fix(kafkaclient): do not close logs channel

- featureflag/featureflag.go
We had some panics in Buildbot from https://github.com/netlify/buildbot/pull/915 because Buildbot expects the client to present even when it isn't successfully initiated.
When that's the case, it will return `false` for flags, eg https://godoc.org/gopkg.in/launchdarkly/go-client.v4#LDClient.BoolVariation
> BoolVariation returns the value of a boolean feature flag for a given user. Returns defaultVal if there is an error, if the flag doesn't exist, the client hasn't completed initialization, or the feature is turned off and has no off variation. 
Proceeding with flags set to false seems preferable to failing the build, and returning the client alongside an error lets consumers of this package decide if they want to proceed or not.
> Return dummy featureflag client on error

- parser/user_traffic.go
- parser/user_traffic_test.go
AID's have dangling comma's at a lower frequency than SID's but happens enough that its still pretty disruptive and worth proactively fixing.
> Proactively trim dangling comma's from AID values

- Dockercompose.test.yml
- Dockerfile.setup
- kafka/consume.go
- kafka/consume_test.go
- kafka/integration_test.go
Integration tests run on Docker via Docker Compose.
There was some issues on the configuration, on how we were creating the kafka topic for testing the `kafka` package, and some other minors (including using version 2 which is outdated).
This PR fixes all known issues and updates the Docker Compose file but also simplifies the configuration for Kafka (only need 1 zookeeper vs 3, removing host-network mode, etc).
It also fixes the integration test.
> chore(ci): improve Docker Compose files for a more robust experience running integration tests

- kafka/README.md
This PR cleans up the README for the kafka package. 
It also adds a note regarding the requirement of using CGO for compiling.
> docs(kafka): update README

- featureflag/config.go
- featureflag/featureflag.go
- featureflag/featureflag_test.go
- featureflag/fixtures/flags.yml
- featureflag/mock.go
- go.mod
- go.sum
In buildbot, we want to start passing feature flags down to netlify build. To do so, we need a method to get all enabled flags for a user. For this particular case, we only care about boolean ones.
This adds a method to the featureflag package to do so. LanuchDarkly's Go SDK provides a way to get all flags for a user, so we wrap that in another method to select just the enabled boolean ones.
For tests, it uses the file config as suggested by LaunchDarkly docs: https://docs.launchdarkly.com/sdk/concepts/flags-from-files
> Add method to get all enabled feature flags for a user

- featureflag/mock.go
Followup to https://github.com/netlify/netlify-commons/pull/187
The MockClient should respect the flags set for it.
> Make featureflag.MockClient return enabled flags in AllEnabledFlags

- kafka/consume.go
- kafka/consume_test.go
- kafka/kafkatest/utils.go
In an effort to help users of our Kafka lib with common use cases, this PR adds a Factory function type, which can be used for postponing the creation of a consumer on runtime. E.g. setting an initial offset that you don't know on boot time.
`NewConsumer` and `NewDetachedConsumer` implements this already.
> feat(kafka): add ConsumerFactory in order to align future developments

- kafka/kafkatest/utils_test.go
This PR adds a simple test around the `WaitForKey` method on the FakeKafkaProducer, located in the `kafkatest` kafka subpackage.
The purpose is valid also to simply show how you can use Pipes and wait for messages to be committed without having to use `time.Sleep` or similar techniques.
cc @aarushik93
> feat(kafka): add test for FakeKafkaProducer WaitForKey

- featureflag/config.go
- featureflag/featureflag.go
Support the LaunchDarkly [relay](https://github.com/launchdarkly/ld-relay) proxy for continuous integration scenarios where you need to flip flags on/off during test runs and ensure propagation. Also allow the telemetry features to be disabled in these scenarios, as they don't work with the relay proxy.
> Support local LD relay and disable telemetry.

- nconf/args.go
- nconf/args_test.go
- nconf/configuration.go
- nconf/configuration_test.go
- nconf/logging.go
I was trying to use this for a silly script, I didn't configure any logging parameters and then this started to panic. This should prevent that
> provide default config for logging

- parser/user_traffic.go
- parser/user_traffic_test.go
Changes the behaviour of the UT parser to collect any unknown kv pairs or unbalanced fields as a slice of unparsed entries (returned in the UserTraffic struct) rather than throwing an error. This is especially helpful since we somewhat frequently have duplicate value fields for keys.
For example - while auditing a sample of log lines for a Peloton site nearly 100% of the "key with no value" errors where from a country code field where the value was a duplicate like `US, US`. 
```
2020/12/04 08:29:30 ==== Errors Seen ====
2020/12/04 08:29:30 key with no value: 6341 
2020/12/04 08:29:30 missing_sid_and_csid: 1926
2020/12/04 08:29:30 lines seen: 19058
2020/12/04 08:29:30 bytes potentially billed: 611126576
2020/12/04 08:29:30 bytes potentially missed: 45379903
```
> Add regex based kv extraction option

- tracing/req_tracer.go
For whatever reason, in order to use the `http.status` tag of a trace span from a datadog dashboard, the status must be written as a string,  not an integer.
See [slack conversation](https://netlify.slack.com/archives/C9D3B8RGF/p1607535957411300).
See https://github.com/netlify/gotrue/pull/272 for equivalent working change in gotrue.
> Set status code as string on spans

- featureflag/config.go
- featureflag/featureflag.go
- featureflag/featureflag_test.go
- go.mod
- nconf/args.go
- nconf/args_test.go
- nconf/bugsnag.go
- nconf/configuration.go
- nconf/configuration_test.go
- nconf/logging.go
- nconf/timeout.go
- nconf/timeout_test.go
- nconf/tls.go
- tracing/config.go
- util/duration.go
- util/duration_test.go
Ok the old code was doing a bytes -> map[string]interface{} -> mapstructure. This was very confusing (and didn't seem to be working?) so this actually just simplifies it to be json/yaml directly.
What it means is that anyone using this will need to add the json/yaml tags to their struct (and can lose the mapstructure). I think that it makes it a bit clearer
> make the config direct from yaml and json

- .github/workflows/build.yml
Addressing @mheffner comment in https://github.com/netlify/go-service-boilerplate/pull/27
Let's make sure that netlify-commons works with 1.16.
We really should fix that flappy tests though, let's see how it goes.
> Add go version 1.16.x to CI

- server/server.go
- server/server_test.go
- allows us to specify the hostname in the server config
- should not break existing config, if the host isn't set, we should still get the same results
> feat: add ability to specify hostname in server

- metriks/distribution.go
- metriks/distribution_test.go
- metriks/metriks.go
fixes: https://github.com/netlify/netlify-commons/issues/208
I decided to do this for only the datadog sink because I think it is where it is most useful. It means other sinks will throw this data away.
Also, yes it is icky global where concurrent invocations would be..odd. We could fix this with some locking but I thought the risk was low enough to not worry about that. Part of me was thinking of storing the `statsd` globally but the other supporting values (e.g. default tags, service name) would have to go with it. If we decide to cut the metrics package we can reconsider this whole thing.
> build in distribution metrics for datadog sink

- .github/workflows/build.yml
- metriks/gauge.go
- metriks/gauge_test.go
- metriks/metriks.go
In a handful of services we've needed a gauge that would report on some scheduled timer. This does that so that we can consistently report sparse gauge values to datadog
> make a persistent gauge

- router/router_test.go
- testutil/logger.go
- testutil/logger_test.go
- tracing/req_tracer_test.go
I was waiting for some humio queries to finish and decided that I'd finally write this. What the goal is to make it easier to inject a logger all over our tests.
There is a lot of
```
func tl(t *testing.T) logrus.FieldLogger {
return logrus.WithField("test", t.Name())
}
```
And `init` blocks that check for the log level in a variety of forms. This is an effort to have to never copy/paste that code again. While I was there I also added some features I think are nice, but I'm open to removing them.
> build a test logger

- kafka/kafkatest/utils.go
- kafka/kafkatest/utils_test.go
**Summary**
I seems the the `FakeKafkaConsumer` will only advance to read the next message if you commit the offset, which isn't how a real consumer is expected to operate.
I added an `uncommitedOffset` to the consumer which will advance after every `FetchMessage`.
> Fix FakeKafkaConsumer to advance through messages

- ntoml/netlify_toml.go
Adds a field to the netlify plugin configuration for the pinned plugin version. Part of https://github.com/netlify/buildbot/issues/1269
> feat: add field for pinned plugin version

- kafka/consume.go
- kafka/kafkatest/utils.go
*Summary:*
Exposing `confluent-kafka-go`'s functionality for asynchronous offset commits.
This is required for https://github.com/netlify/edge-state/issues/306
> feat: allow for asynchronous kafka offset commits

- go.mod
I noticed netlify-commons sets go 1.14 as the minimum version, however the project has v1.15 features and therefore won't allow one to build with v1.14. Our CI also builds with only v1.15 and v1.16
Here is an example of a feature used and only available in v1.15:
The Ticker.Reset function used here -  https://github.com/netlify/netlify-commons/blob/c1a004d0f8e6998d8058e5cc68a0606ed5e67876/metriks/gauge.go#L54 was introduced in golang v1.15 and therefore won’t work when one builds with 1.14
BREAKING CHANGES:
n/a
> Upgrade the minimum golang version required to build(v1.15)

- featureflag/featureflag.go
This PR adds a `AllEnabledFlagsUser` method to the `featureflag` package, which does the same as `AllEnabledFlags` but accepts a LD user as an argument. It follows the same pattern as `Enabled`/`EnabledUser` and `Variation`/`VariationUser`.
We'd need this in buildbot as part of https://github.com/netlify/buildbot/issues/1395.
> feat: add AllEnabledFlagsUser to featureflag

- ntoml/netlify_toml.go
Omit empty pinned versions when serializing build plugins config to JSON.
> fix: omit empty pinned versions

- tracing/config.go
Use `WithService` that doesn't emit a warning.
Fixes component name for logging with Datadog.
> chore: WithServiceName is deprecated

- go.mod
- go.sum
- util/duration.go
- util/duration_test.go
- util/url.go
- util/url_test.go
It's common that we specify URLs in our configurations. This PR adds a serializable URL type, which can be idiomatically marshalled/unmarshalled as json or yaml. 
I also fixed a bug in our Duration type. I reworked the tests so that they now catch such regressions.
> feat: added serializable URL type

- metriks/gauge.go
The race detector picked this up, we must read value with atomic as well.
```
WARNING: DATA RACE
Read at 0x00c000524eb0 by goroutine 7:
github.com/netlify/netlify-commons/metriks.(*PersistentGauge).start()
.../work/src/github.com/netlify/netlify-commons/metriks/gauge.go:67 +0x7a
github.com/netlify/netlify-commons/metriks.NewPersistentGaugeWithDuration·dwrap·1()
.../work/src/github.com/netlify/netlify-commons/metriks/gauge.go:94 +0x58
Previous write at 0x00c000524eb0 by goroutine 8:
sync/atomic.SwapInt32()
.../1.17.1/go/src/runtime/race_amd64.s:280 +0xb
sync/atomic.SwapInt32()
<autogenerated>:1 +0x1a
github.com/netlify/netlify-commons/metriks.TestPersistentGauge()
.../work/src/github.com/netlify/netlify-commons/metriks/gauge_test.go:23 +0x1e4
testing.tRunner() …
```
> Must read value with atomic

- metriks/metriks.go
- metriks/metriks_test.go
- tracing/config.go
This adds an automatic global `service` tag to metrics and traces set to the service name. This provides automatic correlation of metrics and traces emitted by a service so they can be found in DD.
We only set this if the user hasn't already provided a global `service` tag.
> Add service tag to metrics and traces

- featureflag/config.go
- featureflag/featureflag.go
- featureflag/global.go
- featureflag/mock.go
- make it possible to specify custom attributes when calling `featureflag.Enabled` etc, without manually creating the launch darkly user type.
- add config option to specify default attributes that get passed to every `featureflag.Enabled` call
> feature: allow specifying custom featureflag atributes

- server/server.go
I've seen a few panics that seem to be caused by trying to close the `done` channel twice. This should make sure the channel only gets closed once, even if `Shutdown` is called twice.
> fix: panic on server shutdown from closing closed channel

- http/http.go
- http/http_test.go
Closes #266. We now attempt to resolve the hostname, and check all IP addresses returned against the allow list / deny list. 
Note: `net.LookupIP` works for both URLs and IP addresses.
> fix: properly handle urls in saferoundtripper

- kafka/kafkatest/utils.go
This sets the FakeKafkaConsumer#Close to grab the msg mutex lock and lock it before closing the channel. 
This prevents a race between a user closing the consumer and committing
Before we get this datarace:
```==================
WARNING: DATA RACE
Write at 0x00c0001a4310 by goroutine 30:
runtime.closechan()
/usr/local/go/src/runtime/chan.go:355 +0x0
github.com/netlify/netlify-commons/kafka/kafkatest.(*FakeKafkaConsumer).Close()
/home/shane/code/netlify/clickhouse-forwarder/vendor/github.com/netlify/netlify-commons/kafka/kafka
test/utils.go:172 +0x44
github.com/netlify/clickhouse-forwarder/forwarder.(*Forwarder).Stop()
/home/shane/code/netlify/clickhouse-forwarder/forwarder/forwarder.go:134 +0x113
github.com/netlify/clickhouse-forwarder/forwarder.TestStart·dwrap·7() …
```
> Have fakeConsumer.close take the lock before closing the msg chan

- http/http.go
- http/http_test.go
> Add SafeDial to block connections

- tracing/config.go
This was introduced in https://github.com/netlify/netlify-commons/pull/247 to allow applications to
use the datadog tracing api directly instead of an opentracing compatible version.
The issue is that when `UseDatadog` is enabled, opentracing.GlobalTracer is set to a noop tracer
so other packages in netlify-commons that emit traces (e.g router) don't work as expected.
We don't actually need this option because `opentracer.New` already calls `tracer.Start` so
applications should be able to use both the opentracing and datadog tracing api.
> Remove UseDatadog from tracing config

- Makefile
- README.md
**Summary**
The librdkafka library needs to be linked dynamically for M1. See [this comment](https://github.com/confluentinc/confluent-kafka-go/issues/591#issuecomment-951113445) on a github issue.
> fix: Link librdkafka dynamically for M1

- metriks/gauge.go
- metriks/gauge_test.go
Gauges report a snapshot value once per interval, so we don't need to report on every change. There shouldn't be a difference between reporting N times per interval and selecting one vs. simply reporting once. This should reduce overhead of reporting for gauges with high-frequency change rates.
> Report gauges once per interval

- .github/workflows/build.yml
Since many services are already using 1.17, this is important.
> chore: Test on Go 1.17

- .github/renovate.json
The schedule for annoying dependencies was invalid.
The one used now is directly copied from their manual.
> chore: Fix renovate schedule setting

- .github/.kodiak.toml
Kodiak helps us with merging PRs in order. Read more: https://kodiakhq.com/
We have this same config on a lot of other repos.
> chore: Setup kodiak

- .github/workflows/release-please.yml
- Avoid cutting a 1.0.0 with a breaking change
- this matters for Go, because for any further breaking change the import path would change and i don't think that's useful
- Use a different github token
- When using the actions token, no actions will be triggered when release-please makes a PR which leaves the required checks waiting
> chore: Improve release please details

- .github/workflows/release-please.yml
Release-please on main is broken right now, since the Github API token i tried to use in https://github.com/netlify/netlify-commons/pull/301 should not be used anymore.
This new method acquires a token from a github app instead which is much nicer.
> chore: Aquire token for release please on the fly

- router/router_test.go
- tracing/context.go
- tracing/logging.go
- tracing/req_tracer.go
I was debugging some other service I'm starting and noticed that I wanted to validate that (1) the tracer is present and (2) that we're doing the start/finished lines. That made me realize that we're not copying the hooks over. So I fixed that. 
Then I wanted to improve a few things:
- make the tracer package always return a request ID so we can use that to generate missing one
- have a reliable way to get a per-request logger. So export that function.
> chore: update how we get request IDs

- util/headers.go
- util/headers_test.go
It's common that we specify Headers in our yaml/json configurations. This PR adds a serializable http.Header type, which can be idiomatically marshalled/unmarshalled.
> feat: added serializable http.Header type

- router/errors.go
- router/errors_test.go
This PR adds `.WithFields` and `.WithField` methods to `HTTPError`, which act as a facade to Logrus' methods.
They allow to easily add custom log fields to error messages.
At the moment, when you want to add additional information to an HTTP error, you need to print two log lines:
```go
logger.WithError(err).WithField("body", string(body)).Error("error unmarshaling events")
return router.BadRequestError("error parsing body: %s", err.Error())
```
With this PR, we can trim it down to one:
```go
return router.BadRequestError("error parsing body: %s", err.Error()).WithInternalError(err).WithField("body", string(body))
```
(taken from https://github.com/netlify/ingesteer/pull/18#discussion_r813652764)
> feat: HTTPError.WithFields

- nconf/bugsnag.go
This PR adds the hostname to the Bugsnag Configuration for better debugging.
> chore: Add Hostname to Bugsnag Configuration

- featureflag/featureflag.go
- featureflag/featureflag_test.go
- featureflag/mock.go
Adds support for Launch Darkly [IntVariation](https://pkg.go.dev/gopkg.in/launchdarkly/go-server-sdk.v5#LDClient.IntVariation) feature flags
BREAKING CHANGES: none
> feat: Add support for IntVariation feature flags

- featureflag/global.go
- featureflag/global_test.go
- go.mod
- go.sum
Use an ~~rwmutex~~ atomic pointer when accessing the global featureflag client.
> feat: use atomic pointer for global feature flag client

- server/server.go
This PR adds a `config.Router.EnableTracing` field that makes `Router.enableTracing` configurable.
Works towards https://github.com/netlify/ingesteer/issues/152.
There are no breaking changes introduced in this.
> feat: make Router.enableTracing configurable

- metriks/gauge.go
- metriks/gauge_test.go
This was causing some flakiness in the test suite of another service. Because `wg.Add` is called in a separate goroutine there's no guarantee that it gets called before users call `Stop` on the gauge.
> fix: prevent race condition in Stop method on gauge

- README.md
This is to provide notice that these different packages are actively not being maintained and migrated away from. I'd like to remove them but there is a bit of a rats nest of dependencies and until we can move the server/http/router packages (and make them depend on go-*) then it is more work to strip them out. 
So as a stop gap until I get more time to work on this (next first friday?), I wanted to put a notice in the README.
> chore: add removal notice

- .github/workflows/pr-conventions.yml
We are no longer required to label PRs with the type:* label. Removing the automation that supported this.
> chore: remove pr auto labeler action

- ntoml/netlify_toml.go
There's still one place in `buildbot` where the `ntoml.Plugin` is serialized to `json`:
https://github.com/netlify/buildbot/blob/main/messages/cmd_data.go#L41
> fix: add json annotations for ntoml.Plugin
